config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'welcome/about'
  root 'welcome#index'
  resources :lists
  resources :items
  namespace :api, defaults: { format: :json } do

     resources :users do
       resources :lists
     end

     resources :lists, only: [] do
       resources :items, only: [:create, :index, :show, :update]
     end

     resources :items, only: [:destroy]
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>



<<%= select_year(2009) %>
<%= select_year(Time.now) %>

app/views/welcome/index.html.erb
<div class="container-full">

      <div class="row">

        <div class="col-lg-12 text-center v-center">

          <div class="hero-unit"><h1><span class="text-muted">Let's</span> Do.</h1></div>
          <p class = "lead"><span class="text-success">todo.</span><span class="text-warning">api.</span><span class="text-info">simplified.</span></p>

          <br>
                <button class ="btn btn-primary"><%= link_to('Login', new_user_session_path)%></button> <!-- how can I make this link to sign_in?-->
<!-- login form -->

<!--
          <form class="form-inline">
            <div class="form-group">
              <input type="email" class="form-control" id="user_email" placeholder="</email?>">
            </div>
            <div class="form-group">
              <label for="exampleInputPassword2">/</label>
              <input type="text" class="form-control" id="user_password" placeholder="</pass?>">
            </div>
            <button type="submit" class="btn btn-primary">Sign In</button>
          </form>
-->
<!-- end login form -->
        </div>
      </div> <!-- /row -->

      <div class="row">

        <div class="col-lg-12 text-center v-center" style="font-size:39pt;">
          <a href="#"><i class="icon-google-plus"></i></a> <a href="#"><i class="icon-facebook"></i></a>  <a href="#"><i class="icon-twitter"></i></a> <a href="#"><i class="icon-github"></i></a> <a href="#"><i class="icon-pinterest"></i></a>
        </div>

      </div> <!-- /row -->

    <br><br><br><br><br>

</div> <!-- /container full -->

<div class="container">

    <hr>

    <div class="row">
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading"><h3 class="text-success">todo.</h3></div>
            <div class="panel-body">
              Never forget the next <a href="http://www.pokemongo.com/en-us/">Pokemon-Go</a> meetup,
              to wash dishes before your wife comes home, to apply to that dream job,
              to accomplish your fitness goal, or to do anything you might have forgotten had you
              not written it down!
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading"><h3 class ="text-warning">api.</h3></div>
            <div class="panel-body">
              We believe that freedom should be the core of our apps.
              Free as in America. Freedom to
              make todo-list from anywhere you can think of:
              from any laptop, mobile phones, and pretty much any device that is connected to the internet!
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading"><h3 class ="text-info">simplified.</h3></div>
            <div class="panel-body">
              Todo-list should be simple, concise, and take no longer than <a href="http://time.com/3858309/attention-spans-goldfish/">
               eight seconds before you forget it.</a> We cut down the unnecessary work so you can put only the necessary work. That's it.
               The only thing you will have to do is to input the list itself!
            </div>
          </div>
        </div>
    </div>

<hr>
  <div class="row">
        <div class = "col-lg-6">
          <p class = "pull-left"><%= link_to "About", welcome_about_path%> &nbsp; &nbsp; &nbsp; WhoIAm</p>
        </div>
        <div class="col-lg-6">
          <p class="pull-right"><a href="http://www.bootply.com">Template from Bootply</a> &nbsp; ©Copyright 2013 ACME<sup>TM</sup> Brand.</p>
        </div>

    </div>
</div>

<%= link_to "Sign out", destroy_user_session_path, method: 'delete'%>