config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'welcome/about'
  root 'welcome#index'
  resources :lists
  resources :items
  namespace :api, defaults: { format: :json } do

     resources :users do
       resources :lists
     end

     resources :lists, only: [] do
       resources :items, only: [:create, :index, :show, :update]
     end

     resources :items, only: [:destroy]
   end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  validates :name, presence: true
  validates :list, presence: true
end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApiController
  before_action :authenticated?
  respond_to :json

  def index
    list = List.find_by(id: params[:list_id])
    items = list.items
    render json: items, each_serializer: ItemSerializer, adapter: :json
  end

  def show
    list = List.find_by(id: params[:list_id])
    item = list.items.find(params[:id])
    render json: item, each_serializer: ItemSerializer, adapter: :json
  end

  def create
    item = Item.new(item_params)
    if item.save
      render json: item
    else
      render json: { errors: item.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      render json: item
    else
      render json: {errors: item.errors.full_messages}, status: :unprocessable_entity
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :completed, :list_id)
  end

  end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @user = current_user
    @items = current_user.items
  end

  def show
    @user = current_user
    @lists = List.where(user_id: @user.id)
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      flash[:notice] = "Item was saved!"
      redirect_to @item
    else
      flash.now[:alert] = "ERROR. ERROR."
      render :new
    end
  end


  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(item_params)
      flash[:notice] = "Item was updated!"
      redirect_to items_path
    else
      flash.now[:alert] = "WRONG"
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :list_id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Editing items</h1>
<%= @item.name %>
<%= form_for @item do |f| %>
  <%= f.text_field :name, placeholder: "Enter item name" %>
  <%= f.submit "Save", class: "btn btn-success" %>
<% end %>

app/views/items/index.html.erb
<%= @user.name %>
<br>

<% @items.each do |item| %>
  <%= markdown(item.name) %><br>

<% end %>

New items:

<button class= "btn btn-primary"><%= link_to "New Item", new_item_path%></button>

app/views/items/new.html.erb
<div class= "container">
  <%= form_for @item do |f| %>

    <%= f.label :name %> :<br>
    <%= f.text_area :name, size: "24x12" %><br>
    <%= f.label :list_id %> <strong>id</strong> :<br>
    <%= f.select :list_id,  options_for_select([['Home', 1], ['Personal', 2], ['Work', 3]]), {:include_blank => true} %><br>
    <%= f.text_area :list_id %><br>
    <%= f.submit %>

<% end %>
<!-- need to create an additional icon to add new list if user wants a different list from given list! -->


</div>

app/views/items/show.html.erb
<h1>List of items</h1>
<%= markdown(@item.name) %>